name: "Task 2: Ansible Deploy"

on:
  workflow_run:
    workflows: ["Task 1: Terraform Deploy"]
    types: [completed]
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      # ВИМОГА: Перевірка без встановлення (Dry-run)
      - name: Ansible Lint/Check
        run: |
          ansible-playbook -i '${{ secrets.DROPLET_IP }},' playbook.yml --user root --private-key ~/.ssh/id_rsa --check

      # РЕАЛЬНЕ ВСТАНОВЛЕННЯ
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i '${{ secrets.DROPLET_IP }},' playbook.yml --user root --private-key ~/.ssh/id_rsa