name: "Task 2: Ansible Deploy"

on:
  # Автозапуск після успішного Terraform або вручну [cite: 31]
  workflow_run:
    workflows: ["Task 1: Terraform Deploy"]
    types: [completed]
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    # Запуск лише при успіху попереднього етапу
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Налаштування доступу до ВМ через SSH-ключ [cite: 41]
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      # Dry-run: перевірка конфігурації без внесення змін [cite: 38, 39]
      - name: Ansible Lint/Check
        run: |
          ansible-playbook -i '${{ secrets.DROPLET_IP }},' task2/playbook.yml --user root --private-key ~/.ssh/id_rsa --check

      # Основне розгортання K8s, Minikube та Helm [cite: 32, 40]
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i '${{ secrets.DROPLET_IP }},' task2/playbook.yml --user root --private-key ~/.ssh/id_rsa