apiVersion: v1
kind: Namespace
metadata:
  name: release
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-release
  namespace: release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-release
  template:
    metadata:
      labels:
        app: my-app-release
    spec:
      containers:
      - name: app
        image: ${DOCKERHUB_USERNAME}/devops-app:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-release
  namespace: release
spec:
  selector:
    app: my-app-release
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080